### ISSUE TITLE
wrong branch-folder name for CR branches

### ISSUE THREAD

**Issue by ssbarnea** [GerritForge/gerrit-plugin#6]
It seems that current branch name detected by the plugin look like `79/126279/1` instead of just `126279` or something similar. 

The last part indicates the patchset number which should not be part of the branch name, as we do want to build all patchsets from a CR under an unique branch.

The first part (`79/`) is just an implementation detail and does not make sense to be included in the folder name.

Branch name presented on the classic Jenkins ui:
<img width="171" alt="screen shot 2018-01-18 at 18 13 06" src="https://user-images.githubusercontent.com/102495/35114039-55a18edc-fc7b-11e7-8fed-68237a2bf7bd.png">

Branch name presented on new UI (blueocean):
<img width="267" alt="branch-name-blueocean" src="https://user-images.githubusercontent.com/102495/35114148-b0f3baf8-fc7b-11e7-8086-3dc9adf9fe9f.png">

As you can observe in the photo, the branch name in BlueOcean seems to be different than the one in classic UI. Still, it seems that Jenkins UI fails to display it properly because it does cut it off, hiding the most important part of it.

Still I obseved that even on BlueOcean the branch name still contains the patchset number looking like "C-123456/1". Maybe it would be better to drop the suffix and the prefix as this is likely to make it short enough to fit the UI.

**Comment by KenjiTakahashi** [comment]
This so much :-). I was actually surprised that it currently produces new Jenkins branch for every PatchSet in a single Review. Not much useful...

**Comment by lucamilanesio** [comment]
Can't do much for the default view, because Jenkins __requires__ the branch name, which is exactly the one you see there. With regards to BlueOcean, I can drop the leading "C-" and the patch-set at the end. Still it won't be enough to display Gerrit Change Numbers, that are "global" and not per-project as in GitHub. Possibly a PR to the BlueOcean guys?

__P.S. Closing this issue as this repo is going to be dismissed. Any further issues need to be raised on issues.jenkins-ci.org__
